### ISSUE TITLE
research 0 values on cluster, namespace and pod cpu.usage_rate

### ISSUE THREAD

**Issue by bspindler** [metricly/heapster#12]
**Description**
Even though there is load being generated by a pod container, pods, namespaces and clusters show 0 for cpu.usage_rate.

**Steps to reproduce:**
Monitor your kubernetes cluster

**Describe the results you received:**
cpu.usage_rate is 0 

**Describe the results you expected:**
cpu.usage_rate is greater than 0

**Comment by yahonggu** [comment]
the underlying pod container returns cpu/usage_rate while the pod reports it as 0.
![screen shot 2018-06-18 at 11 03 52 am](https://user-images.githubusercontent.com/4582676/41544785-994ad098-72e7-11e8-9d44-b1e189d97734.png)

**Comment by yahonggu** [comment]
This could be related to https://github.com/kubernetes/heapster/issues/1751

**Comment by yahonggu** [comment]
when testing locally using the suggested patch from kuberntes#1751, even though the pod aggregated metrics works now, but there is an extra unexpected pause container created in Metricly:
![screen shot 2018-06-18 at 1 32 59 pm](https://user-images.githubusercontent.com/4582676/41552246-3c8ba99e-72fc-11e8-917b-37a3af7b66f8.png)

see https://www.ianlewis.org/en/almighty-pause-container for what a pause container is.

**Comment by yahonggu** [comment]
We'll apply the patch for pod aggregator to work correctly, then we'll filter out the infra/pause container in the sink.

**Comment by bspindler** [comment]
ok - I think :)
